site_name:           EmpiricalRiskMinimization
repo_url:            https://github.com/reesepathak/EmpiricalRiskMinimization.jl
site_description:    Documentation for EmpiricalRiskMinimization.jl
site_author:         Reese Pathak, Guillermo Angeris, Sanjay Lall, Stephen Boyd.
theme:               readthedocs

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math # For LaTeX

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
